{% set version = "0.4.1" %}

{% set python_min = python_min | default("3.9") %}

package:
  name: litestar-htmx
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/l/litestar-htmx/litestar_htmx-{{ version }}.tar.gz
  sha256: ba2537008eb8cc18bfc8bee5cecb280924c7818bb1c066d79eae4b221696ca08

build:
  number: 0
  noarch: python
  script:
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - hatchling
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}

test:
  source_files:
    - tests
  requires:
    # cfep-25
    - python {{ python_min }}
    # pip/version check
    - pip
    - m2-grep  # [win]
    # circular deps
    - litestar
    # test
    - pytest
    - pytest-cov
    - pytest-sugar
    - pytest-mock
    - pytest-xdist
    # undeclared test deps
    - jinja2
    - mako
  imports:
    - litestar_htmx
  commands:
    - pip check
    - python -c "print(__import__('litestar_htmx.__metadata__').__metadata__.__version__)" | grep -iE {{ version.replace('.', '\.') }}
    - coverage run --source=litestar_htmx --branch -m pytest -vv --color=yes --tb=long
    - coverage report --show-missing --skip-covered --fail-under 92

about:
  home: https://github.com/litestar-org/litestar-htmx
  summary: HTMX Integration for Litesstar
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bollwyvl
    - conda-forge/litestar
